import { IPermissions } from '../../../interfaces/permissions/permissions';
/**
 * Reducer
 * @param state Redux state
 * @param action Action
 */
export declare function permissionsReducer(state: IPermissions | undefined, action: {
    type: string;
    payload: boolean | IPermissions;
}): {
    pointer: boolean | IPermissions;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    pen: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    shape: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    text: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    undoRedo: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    uploadImage: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    partialErase: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    move: boolean | IPermissions;
    pointer: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    clearWhiteboard: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    downloadCanvas: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    erase: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    partialErase: boolean;
    pen: boolean;
    floodFill: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
} | {
    floodFill: boolean | IPermissions;
    pointer: boolean;
    move: boolean;
    erase: boolean;
    partialErase: boolean;
    pen: boolean;
    text: boolean;
    shape: boolean;
    undoRedo: boolean;
    clearWhiteboard: boolean;
    downloadCanvas: boolean;
    uploadImage: boolean;
    backgroundColor: boolean;
    setUserInfoToDisplay: boolean;
    cursorPointer: boolean;
};
