import { PainterEventType } from './PainterEvent';
import { ICanvasObject } from '../../../interfaces/objects/canvas-object';
import { IStampSyncTarget } from '../../../interfaces/stamps/stamp-sync-target';
export interface IPainterController {
    on(event: PainterEventType, listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    removeListener(event: PainterEventType, listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    on(event: 'added', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    on(event: 'moved', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    on(event: 'rotated', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    on(event: 'scaled', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    on(event: 'skewed', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'colorChanged', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    on(event: 'modified', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'fontFamilyChanged', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'removed', listener: (id: string, permission: boolean) => void): this;
    on(event: 'reconstruct', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'moving', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'setToolbarPermissions', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'fontColorChanged', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    on(event: 'lineWidthChanged', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    on(event: 'brushTypeChanged', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'backgroundColorChanged', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'refetch', listener: () => void): this;
    on(event: 'sendStamp', listener: (id: string, target: IStampSyncTarget) => void): this;
    on(event: 'refetch', listener: () => void): this;
    on(event: 'pointer', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'textEdit', listener: (id: string, target: ICanvasObject) => void): this;
    on(event: 'partialErase', listener: (id: string, coordinates: {
        x: number;
        y: number;
    }[]) => void): this;
    on(event: 'cursorPointer', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'added', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    removeListener(event: 'moved', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    removeListener(event: 'rotated', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    removeListener(event: 'scaled', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    removeListener(event: 'skewed', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'colorChanged', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    removeListener(event: 'modified', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'fontFamilyChanged', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'brushTypeChanged', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'backgroundColorChanged', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'removed', listener: (id: string, permission: boolean) => void): this;
    removeListener(event: 'reconstruct', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'moving', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'setToolbarPermissions', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'fontColorChanged', listener: (id: string, objectType: string, target: ICanvasObject) => void): this;
    removeListener(event: 'lineWidthChanged', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'sendStamp', listener: (id: string, target: IStampSyncTarget) => void): this;
    removeListener(event: 'pointer', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'textEdit', listener: (id: string, target: ICanvasObject) => void): this;
    removeListener(event: 'partialErase', listener: (id: string, coordinates: {
        x: number;
        y: number;
    }[]) => void): this;
    removeListener(event: 'refetch', listener: () => void): this;
    removeListener(event: 'cursorPointer', listener: (id: string, target: ICanvasObject) => void): this;
    replayEvents(): Promise<void>;
}
