export const ELEMENTS = {
  ADD_IMAGE_ACTION: 'add_image',
  UNDO_ACTION: 'undo',
  REDO_ACTION: 'redo',
  CLEAR_WHITEBOARD_ACTION: 'clear_whiteboard',
  WHITEBOARD_SCREENSHOT_ACTION: 'whiteboard_screenshot',
  SHARE_WHITEBOARD_ACTION: 'share_whiteboard',
  POINTERS_TOOL: 'pointers',
  MOVE_OBJECTS_TOOL: 'move_objects',
  ERASE_TYPE_TOOL: 'erase_type',
  LINE_TYPE_TOOL: 'line_type',
  THICKNESS_SIZE_TOOL: 'thickness_size',
  FLOOD_FILL_TOOL: 'flood_fill',
  ADD_TEXT_TOOL: 'add_text',
  ADD_SHAPE_TOOL: 'add_shape',
  ADD_STAMP_TOOL: 'add_stamp',
};
