# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      # - name: Install deps
      #   run: | 
      #     apt list --installed|grep pango
      #     sudo apt-get install -y libcairo2-dev libpango-1.0-0 libpangocairo-1.0-0 libpango1.0-dev
      #     apt list --installed|grep pango
      - run: npm i
      - run: npm run build:lib
      - run: npm publish
        env:
          NPM_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
