name: Pull requests

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    install:
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@785cd03160951c320420eedbccfa480951542f62
        secrets:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    test-unit:
        needs: [install]
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-test-jest.yml@785cd03160951c320420eedbccfa480951542f62

    build:
        needs: [install]
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-build-upload-package.yml@785cd03160951c320420eedbccfa480951542f62
